### ISSUE TITLE
Add more tests to the Contracts module

### ISSUE THREAD

**Issue by brunoffranca** [katalchain/katal-chain#75]
1. Add an unit test to the scheduler_run function.
2. Add some fuzzer tests to the main functions (deploy, progress, init).
3. Maybe add some fuzzer tests to the Reals and Time.

**Comment by brunoffranca** [comment]
Also expand the Assets tests.

**Comment by brunoffranca** [comment]
Contracts module tests need to also test the cashflows.

**Comment by retotrinkler** [comment]
Requires test case that reads out `results` using `contract_id` https://github.com/Trinkler/katal-chain/blob/master/modules/contracts/src/contract_types/deploy_pam.rs#L668-L698
